import type { LibraryLesson } from "@/content";

export const pythonIf: LibraryLesson = {
  title: "Python: шарттуу оператор if",
  grade: 8,
  topic: "Шарттуу операторлор",
  content: {
    version: 1,
    duration: 40,
    stages: [
      {
        key: "discover",
        title: "Светофор кантип «чечим» кабыл алат?",
        intro: "Айдоочу ар бир түскө карап башка аракет кылат.",
        minutes: 5,
        blocks: [
          {
            id: "d1",
            type: "text",
            body: "**Кызыл** → машина токтойт.\n\n**Сары** → айдоочу даярданат.\n\n**Жашыл** → машина жолго чыгат.",
          },
          {
            id: "d2",
            type: "open",
            prompt: "Компьютер да ушундай чечим кабыл алышы керек. Ал муну кантип «ойлонот» деп ойлойсуң? Өз сөзүң менен жаз.",
            placeholder: "Мисалы: эгер кызыл болсо, анда…",
            feedback:
              "Туура багыт! Компьютер **шартты** текшерет: шарт туура (True) болсо бир иш кылат, туура эмес (False) болсо башкасын. Python тилинде бул `if` деп жазылат.",
            feedbackCode: 'if tus == "кызыл":\n    print("Токто")\nelif tus == "сары":\n    print("Даярдан")\nelse:\n    print("Жүр")',
          },
        ],
      },
      {
        key: "learning",
        title: "if, elif, else кантип иштейт",
        intro: "Шарттуу оператор программага бир нече жолдун бирин тандоого мүмкүндүк берет.",
        minutes: 10,
        blocks: [
          {
            id: "l1",
            type: "text",
            title: "Сап кандай курулат",
            body: "`if` — ачкыч сөз, андан кийин **шарт** (True же False), акырында **эки чекит** `:`.\n\nШарттан кийинки буйруктар **4 боштук** ичкери жазылат. Python ушул боштук аркылуу кайсы буйрук `if`'ке таандык экенин билет.",
          },
          {
            id: "l2",
            type: "code_example",
            runnable: true,
            caption: "temperatura'нын маанисин өзгөртүп, кайра иштетип көр.",
            code: 'temperatura = 30\nif temperatura > 25:\n    print("Ысык, суу ич")\nelif temperatura > 10:\n    print("Жылуу, сейилдегиле")\nelse:\n    print("Суук, күрмө кий")',
          },
          {
            id: "l3",
            type: "text",
            title: "Салыштыруу операторлору",
            body: "`>` чоң · `<` кичине · `>=` чоң же барабар · `<=` кичине же барабар · `==` барабар · `!=` барабар эмес\n\nPython шарттарды үстүнөн ылдый текшерет. Биринчи True болгон блок аткарылат, калгандары өткөрүлүп кетет.",
          },
          {
            id: "l4",
            type: "mcq",
            prompt: "Python'до шарттан кийин кайсы белги милдеттүү түрдө коюлат?",
            options: [";", ":", "."],
            correct: 1,
            mono: true,
            explain: "Эки чекит `:` «мындан кийин шарттын блогу башталат» дегенди билдирет.",
            xp: 10,
          },
        ],
      },
      {
        key: "practice",
        title: "Колуң менен жаз",
        intro: "Үч тапшырма, жеңилден татаалга. Ар бири автоматтык түрдө текшерилет.",
        minutes: 15,
        blocks: [
          {
            id: "p1",
            type: "mcq",
            prompt: "Бош орунга туура операторду танда.",
            code: 'tus = input("Светофордун түсү: ")\nif tus ___ "кызыл":\n    print("Токто!")',
            options: ["=", "==", "!="],
            correct: 1,
            mono: true,
            explain: "`==` эки маанини салыштырат жана True же False берет.",
            hint: "Бир `=` маани ыйгарат, ал эми `!=` «барабар эмес» дегенди билдирет.",
            xp: 10,
          },
          {
            id: "p2",
            type: "code_task",
            prompt: "Кинотеатрга 18 жаштан баштап киргизишет. `____` ордуна шартты жазып, программаны бүтүр.",
            starter: 'jash = int(input())\nif ____:\n    print("Кире аласыз")\nelse:\n    print("Кечириңиз, али эрте")',
            tests: [
              { input: "12", expected: "Кечириңиз, али эрте" },
              { input: "17", expected: "Кечириңиз, али эрте" },
              { input: "18", expected: "Кире аласыз" },
              { input: "25", expected: "Кире аласыз" },
            ],
            hint: "«18 жаштан баштап» — 18 да кирет. Кайсы оператор «чоң же барабар»?",
            xp: 10,
          },
          {
            id: "p3",
            type: "parsons",
            prompt: "Бааны сөз менен чыгарган программаны түз.",
            lines: [
              "baa = 85",
              "if baa >= 90:",
              '    print("5 — Эң жакшы")',
              "elif baa >= 70:",
              '    print("4 — Жакшы")',
              "else:",
              '    print("3 — Аракет кыл")',
            ],
            xp: 10,
          },
        ],
      },
      {
        key: "reinforce",
        title: "Катаны тап жана натыйжаны болжолдо",
        minutes: 7,
        blocks: [
          {
            id: "r1",
            type: "bug_hunt",
            prompt: "Бул коддо 2 ката бар. Катасы бар саптарды бас.",
            code: 'temperatura = 30\nif temperatura > 25\n    print("Ысык")\nelse:\nprint("Салкын")',
            bugs: [
              { line: 2, explain: "2-сап: шарттан кийин эки чекит `:` жок." },
              { line: 5, explain: "5-сап: `else` ичиндеги буйрук 4 боштук ичкери жазылышы керек." },
            ],
            fixed: 'temperatura = 30\nif temperatura > 25:\n    print("Ысык")\nelse:\n    print("Салкын")',
            xp: 10,
          },
          {
            id: "r2",
            type: "mcq",
            prompt: "Программа эмне чыгарат? (`%` бөлүүдөн калган калдыкты берет: 7 % 2 → 1)",
            code: 'x = 7\nif x % 2 == 0:\n    print("Жуп")\nelse:\n    print("Так")',
            options: ["Жуп", "Так", "Эч нерсе чыкпайт", "Ката чыгат"],
            correct: 1,
            explain: "7 % 2 = 1, демек `1 == 0` → False, ошондуктан `else` блогу иштейт.",
            hint: "Алгач 7 % 2 канча болорун эсепте.",
            xp: 10,
          },
        ],
      },
      {
        key: "exit",
        title: "Сабактан чыгуу билети",
        intro: "Ар бир суроого бир гана жолу жооп бересиң.",
        minutes: 3,
        blocks: [
          {
            id: "e1",
            type: "mcq",
            prompt: "Бардык шарттар False болгондо кайсы блок аткарылат?",
            options: ["if", "elif", "else", "print"],
            correct: 2,
            mono: true,
          },
          {
            id: "e2",
            type: "mcq",
            prompt: "Бул код эмне чыгарат?",
            code: 'a = 5\nif a > 3:\n    print("A")\nelif a > 1:\n    print("B")',
            options: ["A", "B", "A жана B", "Эч нерсе"],
            correct: 0,
          },
          {
            id: "e3",
            type: "mcq",
            prompt: "`=` менен `==` айырмасы эмнеде?",
            options: ["= салыштырат, == маани ыйгарат", "= маани ыйгарат, == салыштырат", "Экөө бирдей иштейт"],
            correct: 1,
          },
          { id: "e4", type: "confidence", prompt: "Бүгүнкү теманы канчалык түшүндүң?" },
          {
            id: "e5",
            type: "open",
            optional: true,
            prompt: "Эмне түшүнүксүз калды?",
            placeholder: "Мисалы: elif качан керек экенин толук түшүнгөн жокмун",
          },
        ],
      },
    ],
  },
};
